# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# some more ls aliases
alias ll='ls -alF'
alias llt='ls -lt'
alias llrt='ls -lrt'
alias llrtapk='ls -lrt *.apk'
alias llrs='ls -lrS'
alias lls='ls -lS'
alias la='ls -A'
alias l='ls -CF'

alias vi='vim'
alias vt='vim -t'

export WEBKIT_PATH=external/webkit/Source
export SOGOUWEBKIT_PATH=external/sogouwebkit/Source
export SOGOULIBS_PATH=external/sogoulibs
export SOGOUWEBVIEW_PATH=/home/bdg/sogouwebview/sogouwebviewforas
export SOGOUSUPPORT_PATH=external/sogoulibs/sogousupport
export SOGOUCHROME_PATH=external/sogouchromium

############### this section should be changed for platform ################
export ANDROID_PATH=~/ssd/android/AndroidSource/
export SOGOU_CHROME_PATH=/home/bdg/ssd/chromium/src
export CHROME_ANDROID_PATH=/home/bdg/ssd/chromium.android_webview/src
export SOGOU_CHROME_PATH_DELEGATE=$SOGOU_CHROME_PATH/sogou_webkit/sogouwebview_delegate

#export ANDROID_IMG_PATH=/home/bdg/ssd/android/android43
export GOOGLE_ANDROID_PATH=/home/bdg/ssd/android/android43
export ANDROID_PRODUCT_OUT=/home/bdg/ssd/android/AndroidSource/out/target/product/generic
############### this section should be changed for platform ################
export ANDROID_IMG_PATH=/home/bdg/ssd/android/android43
export ANDROID_LIB_PATH=${ANDROID_PRODUCT_OUT}/system/lib
export ANDROID_SYM_PATH=${ANDROID_PRODUCT_OUT}/symbols/system/lib

# other's path set
export WORKSPACE_PATH=~/workspace/workspace
export PROJECT_PATH=~/sogouwebview/sogouwebview
export APACHE2_PATH=/var/www/
export OTHER_BROWSER_PATH=/home/bdg/other_browser
export CHROMIUM_PATH=/home/bdg/ssd/android/android441/external/chromium_org
export ANDROID_SDK_PATH=~/android-sdk
export ANDROID_GENERATED=out/target/product/generic/obj/STATIC_LIBRARIES/libsogouwebcore_intermediates
############ tmp path####################

alias cdicu="cd ${ANDROID_PATH}/external/icu4c"
################################

alias cdhome="cd ~"
alias cddownload='cd ~/downloads'
alias cdtest='cd ~/test'
alias cdwork='cd /home/bdg/work/tvsohu'
alias cdstudy='cd ~/study/'
alias cdssd='cd ~/ssd/'
alias cddoc='cd ~/doc/'
alias cdsdk="cd ${ANDROID_SDK_PATH}"
alias cdtmp="cd ~/ssd/tmp"
alias cdbin="cd ~/bin"
alias cdworkspace="cd ${WORKSPACE_PATH}"
alias cdproject="cd ${PROJECT_PATH}"
alias cdrel="cd /home/bdg/ssd/shell/release5.3.0"
alias cdshell="cd /home/bdg/ssd/shell/trunk"
alias cdchromesdk="cd /home/bdg/ssd/shell/chromium"
alias cdwzhang="cd /home/bdg/wzhang"
alias cddebug="cd /home/bdg/ssd/android/android441"
alias cdother-browser="cd ${OTHER_BROWSER_PATH}/"
alias cdapache2="cd ${APACHE2_PATH}"

alias cdgenerated="cd ${ANDROID_PATH}/${ANDROID_GENERATED}"
alias cdandroid="cd ${ANDROID_PATH}"
alias cdbandroid="cd /home/bdg/ssd/bak/AndroidSource"
alias cdgwebkit="cd ${ANDROID_IMG_PATH}/${WEBKIT_PATH}"
alias cdwebkit="cd ${ANDROID_PATH}/${SOGOUWEBKIT_PATH}"
alias cdbwebkit="cd /home/bdg/ssd/bak/AndroidSource/${SOGOUWEBKIT_PATH}"
alias cdlibs="cd ${ANDROID_PATH}/${SOGOULIBS_PATH}"
alias cdwebview="cd ${SOGOUWEBVIEW_PATH}"
alias cdsupport="cd ${ANDROID_PATH}/${SOGOUSUPPORT_PATH}"
alias cdimg="cd ${ANDROID_PATH}/${ANDROID_IMG_PATH}"
alias cdlib="cd ${ANDROID_PATH}/${ANDROID_LIB_PATH}"
alias cdsym="cd ${ANDROID_PATH}/${ANDROID_SYM_PATH}"
alias cdframe="cd ${ANDROID_PATH}/frameworks/base/core/java/android"

alias cdgandroid="cd ${GOOGLE_ANDROID_PATH}"
alias cdgwebkit="cd ${GOOGLE_ANDROID_PATH}/${WEBKIT_PATH}"
alias cdgsogouwebkit="cd ${GOOGLE_ANDROID_PATH}/${SOGOUWEBKIT_PATH}"
alias cdgsogousupport="cd ${GOOGLE_ANDROID_PATH}/${SOGOUSUPPORT_PATH}"
alias cdgimg="cd ${GOOGLE_ANDROID_PATH}/${ANDROID_IMG_PATH}"
alias cdglib="cd ${GOOGLE_ANDROID_PATH}/${ANDROID_LIB_PATH}"
alias cdgsym="cd ${GOOGLE_ANDROID_PATH}/${ANDROID_SYM_PATH}"
alias cdgframe="cd ${GOOGLE_ANDROID_PATH}/frameworks/base/core/java/android"

#for sogou chrome
alias cdchrome="cd ${SOGOU_CHROME_PATH}"
alias cddl="cd /home/bdg/ssd/dl/chromium"
alias cdscrapy="cd /home/bdg/ssd/dl/chromium/chromium.src/"
alias cddelegate="cd ${SOGOU_CHROME_PATH_DELEGATE}"
alias cdhappyin="cd /home/bdg/ssd/dl/chromium/chromium.src/pro/happy-inn"

alias cdsogouwebview="cd ${CHROME_ANDROID_PATH}"

export USE_CCACHE=1
export CCACHE_DIR=/home/bdg/ccache
#/home/bdg/android/AndroidSource/prebuilts/misc/linux-x86/ccache/ccache -M 30G
#export JAVA_HOME=/usr/lib/jvm/jdk1.6.0_45
export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_161
#export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export ANDROID_HOME=/home/bdg/android-sdk
export JRE_HOME=${JAVA_HOME}/jre
export ANDROID_JAVA_HOME=$JAVA_HOME
export CLASSPATH=.:${JAVA_HOME}/lib:$JRE_HOME/lib:$CLASSPATH
export JAVA_PATH=${JAVA_HOME}/bin:${JRE_HOME}/bin
export JAVA_HOME;
export JRE_HOME;
export CLASSPATH;
HOME_BIN=~/bin/

export ECLIPSE_PATH=~/workspace/eclipse

ANDROID_PRODUCT_OUT_BIN=${ANDROID_PATH}/out/host/linux-x86/bin 
ANDROID_GDBCLIENT=${ANDROID_PATH}/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.6/bin/

export GRADLE_HOME=/opt/gradle-4.6-rc-2
export  PATH=~/bin:$QTDIR/bin:$JAVA_HOME/bin:${ANDROID_GDBCLIENT}:${ANDROID_PRODUCT_OUT_BIN}:${ANDROID_PRODUCT_OUT}:${ECLIPSE_PATH}:$PATH
export  PATH=$PATH:${ANDROID_SDK_PATH}/platform-tools:${ANDROID_SDK_PATH}/tools
export PATH=$PATH:/opt/qq2011/bin:~/dl/bin

DEPOT_TOOLS_PATH=/home/bdg/depot_tools
export PATH=$PATH:$DEPOT_TOOLS_PATH

export PATH=${GRADLE_HOME}/bin:$PATH

#for qt webkit build
#export  QTDIR=/home/bdg/other_browser/qt/qt-everywhere-opensource-src-4.8.0/inst
#export  PATH=$QTDIR/bin:/usr/bin:$PATH
#export  MANPATH=$QTDIR/man:$MANPATH
#export  LD_LIBRARY_PATH=$QTDIR/lib:$LD_LIBRARY_PATH


#for chromium's sogou browser setting
export DEPOT_TOOLS_UPDATE=0

#export NDK_PROJECT_PATH=/home/bdg/ssd/android-ndk-r9c
export NDK_PATH=/home/bdg/ssd/android-ndk-r9c
export NDK_PROJECT_PATH=/home/bdg/ssd/android/AndroidSource/external/sogoulibs/breakpad/android/sample_app
